language: generic

services:
  - docker

script:
  - docker build -t quay.io/adrianlucrececeleste/alpine-hugo:$TRAVIS_BRANCH -t quay.io/adrianlucrececeleste/alpine-hugo:latest .

deploy:
  - provider: script
    script: bash docker_push
    on:
      branch: master