language: generic
distro: xenial

services:
  - docker

addons:
  apt:
    sources:
      - projectatomic
      - sourceline: "ppa:projectatomic/ppa"
    packages:
      - buildah

script:
  - buildah bud -t quay.io/adrianlucrececeleste/alpine-hugo:$TRAVIS_BRANCH -t quay.io/adrianlucrececeleste/alpine-hugo:latest .

deploy:
  - provider: script
    script: bash docker_push
    on:
      tags: true
      branch: master