language: generic
dist: xenial

services:
  - docker

addons:
  apt:
    sources:
      - projectatomic
      - sourceline: "ppa:projectatomic/ppa"
      - sourceline: "deb http://ppa.launchpad.net/projectatomic/ppa/ubuntu xenial main"
        key_url: "https://pgp.key-server.io/download/0x8BECF1637AD8C79D"
    packages:
      - buildah

script:
  - buildah bud -t quay.io/adrianlucrececeleste/alpine-hugo:$TRAVIS_BRANCH -t quay.io/adrianlucrececeleste/alpine-hugo:latest .

deploy:
  - provider: script
    script: bash docker_push
    on:
      tags: true
      branch: master