#!/bin/bash
echo "$QUAY_BOT_PASSWORD" | docker login -u "$QUAY_BOT_USERNAME" --password-stdin quay.io
echo "$GITHUB_PACKAGE_REG_PASSWORD" | docker login -u "$GITHUB_PACKAGE_REG_USERNAME" --password-stdin docker.pkg.github.com
docker push quay.io/adrianlucrececeleste/alpine-hugo
docker push docker.pkg.github.com/adriankoshka/alpine-hugo/alpine-hugo