#!/bin/bash
echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io
echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin quay.io
docker push quay.io/adrianlucrececeleste/alpine-hugo
docker push docker.io/adrianlucrececeleste/alpine-hugo